default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails_crud_pictures_development

test:
  <<: *default
  database: rails_crud_pictures_test
